### ISSUE TITLE
Is there a more detailed tutorial about what should be in %command% section?

### ISSUE THREAD

**Issue by RollingIsland** [tmplshdw/cloud_config_workaround#54]
As the title said, I am not sure what to fill in %command% part. I tried to use "%command%" string directly but it does not work. I am currently playing Nier Automata on my deck and PC.

**Comment by RollingIsland** [comment]
I don't why but my graphic settings are still overwrting each other...

**Comment by gdiazbanuelos** [comment]
The launch command points to the .sh or .bat (depending if on Linux or Windows). 

In Steam you put for that specific game’s launch command:
`\path\to\download\cloud_config_workaround.bat %command%`

So if you have the script from this GitHub repo in your C drive in your documents folder it would be something like:
`C:\Users\username\Documents\scrips\cloud_config_workaround.bat %command%`

for Linux it would point to the .sh script instead of the .bat

**Comment by RollingIsland** [comment]
@gdiazbanuelos 
This sounds exactly what I tried first. But in that case it seems that after the script finished my game was not launched at all.
